openapi: 3.0.0
info:
  title: budget
  version: 1.0.0
servers:
  - url: https://dev.app.budgetcontrol.cloud/api
paths:
  /budgets/stats:
    get:
      summary: Get budget statistics
      description: Retrieve statistics for budgets
      operationId: getBudgetStats
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    total:
                      type: number
                    totalSpent:
                      type: number
                    totalRemaining:
                      type: number
                    totalSpentPercentage:
                      type: string
                    totalRemainingPercentage:
                      type: string
                    budget:
                      type: object
                      properties:
                        id:
                          type: integer
                        uuid:
                          type: string
                        name:
                          type: string
                        description:
                          type: string
                        amount:
                          type: number
                        configuration:
                          type: object
                          properties:
                            tags:
                              type: array
                              items:
                                type: string
                            types:
                              type: array
                              items:
                                type: string
                            period:
                              type: string
                            accounts:
                              type: array
                              items:
                                type: integer
                            categories:
                              type: array
                              items:
                                type: integer
                            period_end:
                              type: string
                              format: date-time
                            period_start:
                              type: string
                              format: date-time
                        deleted_at:
                          type: string
                          format: date-time
                        notification:
                          type: integer
                        workspace_id:
                          type: integer
                        emails:
                          type: array
                          items:
                            type: string
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
                  
security:
  - BearerAuth: []
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT